// This file is auto-generated by @hey-api/openapi-ts

export const ApiErrorSchema = {
  type: "object",
  required: ["message"],
  properties: {
    code: {
      type: ["string", "null"],
      description: "Error code for client handling",
      example: "NOT_FOUND",
    },
    message: {
      type: "string",
      description: "Error message",
      example: "Error message",
    },
  },
} as const;

export const CardSchema = {
  type: "object",
  required: ["id", "title", "number", "kind", "rarity", "deckId"],
  properties: {
    artist: {
      type: ["string", "null"],
      example: "Sergei Leoluch Panin",
    },
    deckId: {
      type: "string",
      format: "uuid",
      example: "123e4567-e89b-12d3-a456-426614174003",
    },
    description: {
      type: ["string", "null"],
      example:
        "Whenever The Wise Mothman enters the battlefield or attacks, each player gets a rad counter.",
    },
    id: {
      type: "string",
      format: "uuid",
      example: "123e4567-e89b-12d3-a456-426614174003",
    },
    kind: {
      type: "string",
      example: "Legendary Creature — Insect Mutant",
    },
    mana: {
      type: ["array", "null"],
      items: {
        type: "string",
      },
      example: "1, B, G, U",
    },
    number: {
      type: "integer",
      format: "int64",
      example: "0004",
    },
    power: {
      type: ["string", "null"],
      example: "3",
    },
    rarity: {
      type: "string",
      example: "M",
    },
    title: {
      type: "string",
      example: "The Wise Mothman",
    },
    toughness: {
      type: ["string", "null"],
      example: "3",
    },
  },
} as const;

export const DeckSchema = {
  type: "object",
  required: ["id", "name", "code", "release"],
  properties: {
    code: {
      type: "string",
      example: "PIP",
    },
    id: {
      type: "string",
      format: "uuid",
      example: "123e4567-e89b-12d3-a456-426614174003",
    },
    name: {
      type: "string",
      example: "Fallout",
    },
    release: {
      type: "string",
      format: "date-time",
      example: "2024-01-01T00:00:00Z",
    },
  },
} as const;

export const PaginatedResponse_CardSchema = {
  type: "object",
  required: ["page", "total", "totalPages", "data"],
  properties: {
    data: {
      type: "array",
      items: {
        type: "object",
        required: ["id", "title", "number", "kind", "rarity", "deckId"],
        properties: {
          artist: {
            type: ["string", "null"],
            example: "Sergei Leoluch Panin",
          },
          deckId: {
            type: "string",
            format: "uuid",
            example: "123e4567-e89b-12d3-a456-426614174003",
          },
          description: {
            type: ["string", "null"],
            example:
              "Whenever The Wise Mothman enters the battlefield or attacks, each player gets a rad counter.",
          },
          id: {
            type: "string",
            format: "uuid",
            example: "123e4567-e89b-12d3-a456-426614174003",
          },
          kind: {
            type: "string",
            example: "Legendary Creature — Insect Mutant",
          },
          mana: {
            type: ["array", "null"],
            items: {
              type: "string",
            },
            example: "1, B, G, U",
          },
          number: {
            type: "integer",
            format: "int64",
            example: "0004",
          },
          power: {
            type: ["string", "null"],
            example: "3",
          },
          rarity: {
            type: "string",
            example: "M",
          },
          title: {
            type: "string",
            example: "The Wise Mothman",
          },
          toughness: {
            type: ["string", "null"],
            example: "3",
          },
        },
      },
    },
    page: {
      type: "integer",
      format: "int64",
      minimum: 0,
    },
    total: {
      type: "integer",
      format: "int64",
      minimum: 0,
    },
    totalPages: {
      type: "integer",
      format: "int32",
      minimum: 0,
    },
  },
} as const;

export const PaginatedResponse_DeckSchema = {
  type: "object",
  required: ["page", "total", "totalPages", "data"],
  properties: {
    data: {
      type: "array",
      items: {
        type: "object",
        required: ["id", "name", "code", "release"],
        properties: {
          code: {
            type: "string",
            example: "PIP",
          },
          id: {
            type: "string",
            format: "uuid",
            example: "123e4567-e89b-12d3-a456-426614174003",
          },
          name: {
            type: "string",
            example: "Fallout",
          },
          release: {
            type: "string",
            format: "date-time",
            example: "2024-01-01T00:00:00Z",
          },
        },
      },
    },
    page: {
      type: "integer",
      format: "int64",
      minimum: 0,
    },
    total: {
      type: "integer",
      format: "int64",
      minimum: 0,
    },
    totalPages: {
      type: "integer",
      format: "int32",
      minimum: 0,
    },
  },
} as const;
