// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import { retrieveCardsResponseTransformer, retrieveDecksResponseTransformer } from './transformers.gen';
import type { RetrieveCardsData, RetrieveCardsErrors, RetrieveCardsResponses, RetrieveDecksData, RetrieveDecksErrors, RetrieveDecksResponses, RetrieveImageData, RetrieveImageErrors, RetrieveImageResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export const retrieveCards = <ThrowOnError extends boolean = false>(options?: Options<RetrieveCardsData, ThrowOnError>) => {
    return (options?.client ?? client).get<RetrieveCardsResponses, RetrieveCardsErrors, ThrowOnError>({
        responseTransformer: retrieveCardsResponseTransformer,
        url: '/api/v0/mtg/cards',
        ...options
    });
};

/**
 * Get all Decks with filtering
 */
export const retrieveDecks = <ThrowOnError extends boolean = false>(options?: Options<RetrieveDecksData, ThrowOnError>) => {
    return (options?.client ?? client).get<RetrieveDecksResponses, RetrieveDecksErrors, ThrowOnError>({
        responseTransformer: retrieveDecksResponseTransformer,
        url: '/api/v0/mtg/decks',
        ...options
    });
};

export const retrieveImage = <ThrowOnError extends boolean = false>(options: Options<RetrieveImageData, ThrowOnError>) => {
    return (options.client ?? client).get<RetrieveImageResponses, RetrieveImageErrors, ThrowOnError>({
        url: '/api/v0/mtg/image/{deck_id}/{card_id}',
        ...options
    });
};
