// This file is auto-generated by @hey-api/openapi-ts

import type { RetrieveCardsResponse, RetrieveDecksResponse } from "./types.gen";

export const retrieveCardsResponseTransformer = async (
  data: any,
): Promise<RetrieveCardsResponse> => {
  data = paginatedResponseCardSchemaResponseTransformer(data);
  return data;
};

const paginatedResponseCardSchemaResponseTransformer = (data: any) => {
  data.data = data.data.map((item: any) => {
    item.number = BigInt(item.number.toString());
    return item;
  });
  data.page = BigInt(data.page.toString());
  data.total = BigInt(data.total.toString());
  return data;
};

export const retrieveDecksResponseTransformer = async (
  data: any,
): Promise<RetrieveDecksResponse> => {
  data = paginatedResponseDeckSchemaResponseTransformer(data);
  return data;
};

const paginatedResponseDeckSchemaResponseTransformer = (data: any) => {
  data.data = data.data.map((item: any) => {
    item.release = new Date(item.release);
    return item;
  });
  data.page = BigInt(data.page.toString());
  data.total = BigInt(data.total.toString());
  return data;
};
