// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:7878' | 'https://api.deckmaster.leoborai.com' | (string & {});
};

export type ApiError = {
    /**
     * Error code for client handling
     */
    code?: string | null;
    /**
     * Error message
     */
    message: string;
};

export type Card = {
    artist?: string | null;
    deckId: string;
    description?: string | null;
    id: string;
    kind: string;
    mana?: Array<string> | null;
    number: bigint;
    power?: string | null;
    rarity: string;
    title: string;
    toughness?: string | null;
};

export type Deck = {
    code: string;
    id: string;
    name: string;
    release: Date;
};

export type PaginatedResponseCard = {
    data: Array<{
        artist?: string | null;
        deckId: string;
        description?: string | null;
        id: string;
        kind: string;
        mana?: Array<string> | null;
        number: bigint;
        power?: string | null;
        rarity: string;
        title: string;
        toughness?: string | null;
    }>;
    page: number;
    total: number;
    totalPages: number;
};

export type PaginatedResponseDeck = {
    data: Array<{
        code: string;
        id: string;
        name: string;
        release: Date;
    }>;
    page: number;
    total: number;
    totalPages: number;
};

export type RetrieveCardsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * ID for the card
         */
        id?: string | null;
        /**
         * Title for the card
         */
        title?: string | null;
        /**
         * Wether to group by Deck ID
         */
        unique?: boolean | null;
    };
    url: '/api/v0/mtg/cards';
};

export type RetrieveCardsErrors = {
    /**
     * Invalid query parameters
     */
    400: ApiError;
};

export type RetrieveCardsError = RetrieveCardsErrors[keyof RetrieveCardsErrors];

export type RetrieveCardsResponses = {
    /**
     * List of MTG Cards
     */
    200: PaginatedResponseCard;
};

export type RetrieveCardsResponse = RetrieveCardsResponses[keyof RetrieveCardsResponses];

export type RetrieveDecksData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page number (starts from 1)
         */
        page?: number | null;
    };
    url: '/api/v0/mtg/decks';
};

export type RetrieveDecksErrors = {
    /**
     * Invalid query parameters
     */
    400: ApiError;
};

export type RetrieveDecksError = RetrieveDecksErrors[keyof RetrieveDecksErrors];

export type RetrieveDecksResponses = {
    /**
     * List of MTG Decks
     */
    200: PaginatedResponseDeck;
};

export type RetrieveDecksResponse = RetrieveDecksResponses[keyof RetrieveDecksResponses];

export type RetrieveImageData = {
    body?: never;
    path: {
        card_id: string;
        deck_id: string;
    };
    query?: never;
    url: '/api/v0/mtg/image/{deck_id}/{card_id}';
};

export type RetrieveImageErrors = {
    /**
     * Invalid query parameters
     */
    400: ApiError;
};

export type RetrieveImageError = RetrieveImageErrors[keyof RetrieveImageErrors];

export type RetrieveImageResponses = {
    /**
     * Retrieves an image from storage
     */
    200: Array<number>;
};

export type RetrieveImageResponse = RetrieveImageResponses[keyof RetrieveImageResponses];
